### ISSUE TITLE
reindex command and dexteritytextindexer don't play well together

### ISSUE THREAD

**Issue by gforcada** [collective/collective.solr#116]
While trying to migrate a plone site to Solr (900k documents) with ``./bin/instance solr_reindex`` all documents get indexed at Solr **but** ``SearchableText`` is empty in my dexterity content types that use ``collective.dexteritytextindexer``.

Probably related to https://github.com/collective/collective.dexteritytextindexer/issues/12 ?

**Comment by gforcada** [comment]
Oh forgot to add: reindexing through the web (i.e. ``http://localhost:8080/Plone/@@solr-maintenance/reindex``) works like a charm, so it has to be something like the issue I linked above.

**Comment by gforcada** [comment]
It was this bug https://github.com/collective/collective.dexteritytextindexer/pull/14 already merged and released (2.0.2): https://pypi.python.org/pypi/collective.dexteritytextindexer

**Comment by tomgross** [comment]
@gforcada Can we close this issue?

**Comment by gforcada** [comment]
Yes, I forgot to do so when I fixed dexteritytextindexer
