### ISSUE TITLE
indexer.py line 121 throws 'Uncommitted changes' when trying to index a new file

### ISSUE THREAD

**Issue by sroney5250** [collective/collective.solr#120]
I am using the latest version of collective.solr.  My SOLR server and Plone server are located on different linux systems.  I tried to index a file and received an error at line 121 of indexer.py.  It seems like calling the function blob.committed() is causing the problem.  How can this be fixed?

**Comment by sroney5250** [comment]
I added a constant under the logger line:

`logger = getLogger('collective.solr.indexer')

SAVEPOINT_SUFFIX = ".spb"
`

I changed the getpath function to the following and now it works.  


`    def getpath(self):
        field = self.context.getPrimaryField()
        blob = field.get(self.context).blob
        if (blob._p_blob_uncommitted
            or
            not blob._p_blob_committed
            or
            blob._p_blob_committed.endswith(SAVEPOINT_SUFFIX)
            ):
                return blob._p_blob_uncommitted
        else:
            return blob.committed() or blob._p_blob_committed
`

**Comment by gforcada** [comment]
@sroney5250 I hope you don't mind that I edited your last comment, for making preformatted text you need to put the code in triple backticks

**Comment by tomgross** [comment]
I have seen this behavior too. I'll look into it.
