### ISSUE TITLE
ISearch utility

### ISSUE THREAD

**Issue by tomgross** [collective/collective.solr#125]
When querying Solr a utility _ISearch_ is used for building the search query and actually quering Solr. It was introduced with https://github.com/collective/collective.solr/commit/df834b9570e630624f631fefb0f92bb5c67a43ed as a global utility
Meanwhile it changed to a local utility because there were issues with AJAX calls to search (together with eea.facetednavigation). Occassionally the utility can not be found and the dispatcher falls back to the catalog implementation.
Here is my question: Does the ISearch instance really have to be a utility? I guess it was introduced for memory saving purpose and/or performance? Or is there a usecase to override it?
Since it is the most stable solution I found I want to replace the utility getter of ISearch in the dispatcher with a standard instance. Any objections, ideas?

**Comment by tisto** [comment]
@witsch can you shed some light into this?

**Comment by witsch** [comment]
Phew, good things I put some docstrings in there to help me remember… :)

The idea behind the (back then) adapter was that the monkey-patch for `searchResults` would eventually be merged upstream.  If I remember correctly there was even a ticket for that at some point.  This would have made the monkey-patching obsolete and allow add-ons dealing with searches (like c.solr) to override search behaviour.

In my opinion that would still be a good thing to have, if only to avoid the monkey-patch.  However, if the former adapter has really been changed into a utility by now, the original point might have been lost somewhere on the way…

**Comment by witsch** [comment]
Ok, it looks like it's actually still the same, i.e. adapter and monkey-patch in place and all.  So, if you ask me I'd keep it that way and try to find out why the adapter can't be found at times.  To me this sounds like the registry might be missing, which is likely to cause other problems eventually anyway.  Iow, rather try to find the cause and don't fix the symptoms…

When do you get that behaviour?  Just during tests or in 'real life' as well?  And do you have steps to reproduce it?

**Comment by gforcada** [comment]
There's a PLIP to merge collective.solr into Plone core: https://github.com/plone/Products.CMFPlone/issues/1343

**Comment by tomgross** [comment]
@witsch The behavior occurs if you do search from AJAX requests. Unfortunately does not occur 100% of the time.

These changes improved the situation:
https://github.com/collective/collective.solr/commit/9ba8bda4615ec9ba7bd316465a8d0fba42cc0665#diff-4f4b1d47a08cc0c9a764a45042fbe04b
https://github.com/collective/collective.solr/commit/053ab265ff7ca6b0a67ac0f0a5a181cff6741301#diff-333e42785857c50ececa8d2e1bb98504

but still the error occurs occasionally. Espacially if c.solr is used together with eea.facetdnavigation which has AJAX calls all over the place.

**Comment by tomgross** [comment]
I don't see this on new installations. I guess it is an edge case legacy issue. Closing this for now.
