### ISSUE TITLE
Plone 5 compatibility

### ISSUE THREAD

**Issue by tisto** [collective/collective.solr#128]
The current master is compatible with Plone 5 and comes with an new React-based search page.

Roadmap:

- [x] Create 5.x branch from current master
- [x] Merge this pr and make it the new master branch
- [x] Release plone.restapi 1.0a1
- [x] Make this pr use plone.restapi 1.0a1
- [x] Fix remaining test isolation issues
- [x] Make sure we do not skip any tests
- [x] Make sure test coverage is > 90 % (as it was before the refactoring)
- [x] Code cleanup
- [x] Remove support for old Plone versions (< 4)
- [x] Remove support for old Solr versions (< 4)
- [x] Remove skins folder
- [x] Remove browser views for Plone 4
- [x] Remove search profile
- [x] Release collective.solr 6.0 with Plone 5 support and a new react-based search UI
- [ ] Upgrade step to remove utilities and move settings to registry

**Comment by tomgross** [comment]
Isn't the skin folder needed for the boosting script?

**Comment by tisto** [comment]
@tomgross yes. we would need to refactor that in order to be able to get rid of skins folder.

**Comment by gforcada** [comment]
@tisto @tomgross I added a new item: upgrade step to move settings and so on

**Comment by tomgross** [comment]
@gforcada I'm not sure we need this. I'm slightly in favor of documenting to uninstall c.solr when upgrading and install afterwards.

**Comment by gforcada** [comment]
@tomgross if that's the best approach that's fine for me, but then the uninstall should really uninstall everything that is installed then :-) so a clean uninstall profile would be needed.

**Comment by tomgross** [comment]
Blocker for 6.0alpha1 release is #144

**Comment by tomgross** [comment]
6.0a1 is released. 🎉 Thanks @tisto !
