### ISSUE TITLE
Revisit lazycat patch in monkey.py

### ISSUE THREAD

**Issue by tomgross** [collective/collective.solr#141]
AFAIK the experimental.catalogqueryplan has been merged to ZCatalog. I guess the patch here in monkey.py can be removed. Any opinions? @hannosch can you help here please?

**Comment by hannosch** [comment]
Looking at this, there are two related patches for the `Lazy/Cat.__add__` methods here.

One that checks for the presence of experimental.catalogqueryplan, and if it's present patches the lazy classes inside that package. That condition and patch can certainly go.

The other related patch applies the same change to the Lazy classes inside of Products.ZCatalog. That is ok for Zope 2.13/Products.ZCatalog 2.x/3.x. In more recent versions of those the Lazy module has moved and is now inside `ZTUtils.Lazy` (inside the Zope project).

I think the easiest way to get rid of all of these patches, would be to change the SolrResponse class in collective.solr and let it be a subsclass of Lazy. That way the `__add__` wouldn't have to be patched, as the `isinstance` check would succeed.

**Comment by tomgross** [comment]
Fixed in #143
