### ISSUE TITLE
Plone 5.1 compatibility

### ISSUE THREAD

**Issue by gforcada** [collective/collective.solr#166]
Just to leave a note here: as the PLIP (https://github.com/plone/Products.CMFPlone/issues/1343) got merged collective.solr, for Plone 5.1 should use Products.CMFCore rather than collective.indexing.

**Comment by tisto** [comment]
PR: https://github.com/collective/collective.solr/pull/183

**Comment by reinhardt** [comment]
See my question in #217

**Comment by reinhardt** [comment]
Following up from #217:

> I'd try to keep both Plone 4.3/5.0 and 5.1/5.2 compatibility if possible.

That would be great of course. But how? We would have to do some kind of conditional dependency in setup.py, and while I think that might be possible, I can't think of a way that wouldn't be hacky and not particularly future proof. Or do we unconditionally depend on collective.indexing and take a lot of care that the imports are set up in a way that doesn't accidentally trigger monkey patches or other shenanigans? That sounds rather fragile.

Maintaining two branches is of course more work but it sounds saner to me atm.

**Comment by tisto** [comment]
@reinhardt I am fine with branching. If we have a mergeable PR we can branch the current master in a pre Plone 5.1 version and master who works with Plone 5.1/5.2.

If you have any questions or want to discuss how to proceed we can also do a call or hangout. Just ping me on hangouts or give me a call (you can find my phone number here: https://kitconcept.com/).

**Comment by tisto** [comment]
@reinhardt FYI: conditional dependencies in setup.py are possible. See for instance: https://github.com/plone/Products.CMFPlone/blob/master/setup.py#L142
