### ISSUE TITLE
suggest-terms view inconsistent API

### ISSUE THREAD

**Issue by jjmurre** [collective/collective.solr#176]
The suggest-terms view return values in the following Json format:
[{'value': {u'freq': 24, u'word': u'water'}, 'label': {u'freq': 24, u'word': u'water'}}]

However, when the 'correctly_spelled' flag is True, the return value is a simple list of strings.
This does not seem very consistent and causes trouble when calling the view.

**Comment by tisto** [comment]
@jjmurre you are correct. Though, this is the way Solr returns the values. We could of course manipulate the response to make it consistent. Though, we decided against this to keep things simple.
