### ISSUE TITLE
New Release 5.0.x

### ISSUE THREAD

**Issue by elioschmutz** [collective/collective.solr#177]
We should have a new bugfix release of `collective.solr` for the 5.x branch (5.0.3 => 5.0.4).

@tisto could you do such a release within the next days (I've got no permissions to do this new release)?

**Comment by tisto** [comment]
@elioschmutz sorry, totally missed that. Feel free to contact me directly via email if I don't respond here. Sometimes I miss mentions on github. You mean this branch, right?

https://github.com/collective/collective.solr/tree/5.x

**Comment by elioschmutz** [comment]
@tisto np! Yes, exactly 👍

**Comment by maethu** [comment]
@tisto a 5.0.4 would be cool 😊

**Comment by tisto** [comment]
Any idea in which branch we have the 5.0.x series? I just checked the 5.x
branch and it contains c.solr 7.0.0a3.

**Comment by tisto** [comment]
Local problem. 5.0.4 is released.
