### ISSUE TITLE
Changing review_state from folder_contents doesn't update solr index

### ISSUE THREAD

**Issue by cekk** [collective/collective.solr#190]
Current environment:
- Plone 5.1rc2
- collective.solr 6.0ra2 (last available pypi version)
- solr 7.*

I noticed that when i try to update a content review_state from folder_contents popup, the index is not updated on solr, and the state is unchanged.

I've seen that when i try to update a state from folder_content's [action](https://github.com/plone/plone.app.content/blob/master/plone/app/content/browser/contents/workflow.py#L70), solr receive the following body call:

    <commit/>

but when i try to update an item from the toolbar's action, i see a more complex call with a complete reindex of the object:

    <add><doc>..a list of all fields..</doc></add><commit/>

The two methods uses different approaches, and seems that the one in folder_contents doesn't trigger the event needed by c.solr to correctly reindex the object.

Any idea about how to handle this case? Anyone else has found this behavior?

**Comment by ale-rt** [comment]
I bet you will need to backport this patch I made for collective.indexing: https://github.com/plone/collective.indexing/pull/17

**Comment by cekk** [comment]
I've found the source of my problem.

I had a required field in solr schema (id).
When i change review state from folder_contents, a reindexObject(idxs=['review_state']) is fired.
c.solr's [index method](https://github.com/collective/collective.solr/blob/master/src/collective/solr/indexer.py#L223) check if there are all the required indexes in the query, and if not, it doesn't update the solr index.

reindexObject doesn't pass 'id' key, so the index is never updated.

The funny thing is that if i try to update a review state from the toolbar, that method will fire reindexObject() without indexes list, and this will produce an index update in solr because is correctly handled [here](https://github.com/collective/collective.solr/blob/master/src/collective/solr/indexer.py#L353)

btw my fix was to set _id_ key in solr schema as not required.
