### ISSUE TITLE
Implementing a search delay in @@search view

### ISSUE THREAD

**Issue by sauzher** [collective/collective.solr#199]
The new React @@search view fires a search immediatly after every keypress in searchbox.
With more than tens of tousands objects indexed, the user experience is really compromised.

So two consideration:
1) is it right to start a search at the very first character inputted? 
2) perhaps 500-1000ms delay from last inputted character is enough to let the user ends the search term string.

So, I'd consider to add theese two parameters into solr-controlpanel and to adapting @@search view according to them:
 - minimum characters to start search from (default 2)
 - search delay in ms (default 500)

alessandro.

**Comment by tisto** [comment]
@sauzher we had that issue in a recent client project (with a custom react search UI). @robgietema @sneridagh can we share our code somehow to integrate that into the c.solr React search UI?

**Comment by sauzher** [comment]
Great!
Furthermore, just found that the [search] submit button is uneffective too.

**Comment by sauzher** [comment]
@tisto @robgietema @sneridagh any effort into this so far? if you have some code to share, I'll be happy to merge that into solr search view.

**Comment by sauzher** [comment]
just found a proper react-delay-input component. 
I'm just working on this here https://github.com/sauzher/collective.solr/tree/fix-issue-199

**Comment by tisto** [comment]
@sauzher please do! We are happy to review and merge!

**Comment by sauzher** [comment]
https://github.com/collective/collective.solr/pull/204

hth
