### ISSUE TITLE
[Plone 5.2-rc2] No module named 'bbb'

### ISSUE THREAD

**Issue by NicolasGoeddel** [collective/collective.solr#236]
Hi,

I just installed a fresh Plone 5.2-rc2 with Python 3.6 and Postgres as Relstorage. It works great, but after adding the egg 'collective.solr' I get this error:
```
  ...
  File "/home/bfd/plone/buildout-cache/eggs/Products.Archetypes-1.16.1-py3.6.egg/Products/Archetypes/__init__.py", line 2, in <module>
    import bbb
ModuleNotFoundError: No module named 'bbb'
```
This is my buildout.cfg
```
[buildout]
extensions =
    buildout.sanitycheck

extends =
    base.cfg
    release-5.2.0-versions.cfg

find-links +=
    http://dist.plone.org/release/5.2.0

buildout-user = user
need-sudo = no

eggs =
    Plone
    Pillow
    RelStorage[postgresql]
    collective.solr

zcml =
#    plone.reload

develop =
#    src/my.package

var-dir=${buildout:directory}/var

backups-dir=${buildout:var-dir}

user=admin:***

deprecation-warnings = off

verbose-security = off

parts =
    client1
    client2
    repozo
    backup
    zopepy
    unifiedinstaller

[instance_relstorage]
<= instance_base
recipe = plone.recipe.zope2instance
rel-storage =
    type postgresql
    dsn dbname='database' user='user' password='***'

[client1]
<= instance_relstorage
http-address = 8080

[client2]
<= instance_relstorage
http-address = 8081

[versions]

buildout.sanitycheck = 1.0.2
collective.recipe.backup = 4.1.0
plone.recipe.unifiedinstaller = 5.2b1
```
I also tried adding the following lines but these files are not available. So the installation documention seems to be outdated.
```
  https://raw.githubusercontent.com/collective/collective.solr/master/solr.cfg
  https://raw.githubusercontent.com/collective/collective.solr/master/solr-4.10.x.cfg
```
What am I missing? What am I doing wrong? What information do you need from me to help me?

**Comment by NicolasGoeddel** [comment]
With version 8.0.0a1 Plone is able to start but I don't know if it is a good idea to use an alpha version at the moment. ;-)

**Comment by tisto** [comment]
@NicolasGoeddel 7.0.0x is also in alpha so you don't have much of a choice right now if you want to use a recent version of Solr. We are using 8.0.0a1 in pre-production right now and it might already be a better choice than 7.x. That's just my 2c though.

**Comment by NicolasGoeddel** [comment]
I close that because it's an issue with an older version and with 8.0.0a1 it works perfectly fine.
