### ISSUE TITLE
Disable react based search

### ISSUE THREAD

**Issue by pbauer** [collective/collective.solr#244]
The react-based search-page has very little benefit over the default in Plone and is missing i18n and quicksearch. 

I removed the react-based search-page and the search-viewlet in my last project by adding the following to  a `overrides.zcml`. This restores the default behavior and still uses solr.

```xml
    <browser:page
        name="search"
        class="Products.CMFPlone.browser.search.Search"
        permission="zope2.View"
        for="plone.app.layout.navigation.interfaces.INavigationRoot"
        template="templates/search.pt"
        layer="collective.solr.browser.interfaces.IThemeSpecific"
        />

    <browser:viewlet
        name="plone.searchbox"
        manager="plone.app.layout.viewlets.interfaces.IPortalHeader"
        class="plone.app.layout.viewlets.common.SearchBoxViewlet"
        permission="zope2.View"
        layer="collective.solr.browser.interfaces.IThemeSpecific"
        />
```

I wonder: Why would anyone use the react-based search page and viewlet? Should we remove them?

**Comment by sauzher** [comment]
+1 for removal.

**Comment by tisto** [comment]
@pbauer the react search allows the user to see search results within milliseconds. You get a Solr-like search experience on top of a standard Plone for free. The React search is also a good base to write a customized search (which we do almost 100% of the time). This was the reason we shared the React search. We actually never used it in any project as far as I know. The way to go IMHO is to solve the open problems of the React search.
