### ISSUE TITLE
Multi-Core possible?

### ISSUE THREAD

**Issue by adrianschulz** [collective/collective.solr#262]
I would like to setup collective.solr with multiple cores.

I found [https://community.plone.org/t/collective-solr-and-solr-version/3633](https://community.plone.org/t/collective-solr-and-solr-version/3633) but since then a lot changed in collective.solr. 

What's the current state regarding multiple cores? Is it possible? How? Does it have any limitations?

**Comment by tisto** [comment]
@adrianschulz Solr supports multi-core configurations out of the box. I do not see any reason why a proper Solr multi-core or Solr could configuration should not work with c.solr.

**Comment by adrianschulz** [comment]
@tisto I thought about querying multiple cores. Accorrding to [https://training.plone.org/5/solr/solr-configuration.html](https://training.plone.org/5/solr/solr-configuration.html) a setup with multiple cores is possible, but searching and indexing is only possible for the default core.

**Comment by tisto** [comment]
@adrianschulz I wouldn't rely too much on the c.solr documentation here. Check the Solr docs for a multi-core setup that allows both writing and reading.

**Comment by adrianschulz** [comment]
I found a solution for querying a specific core (I was looking for this). See [Pull Request in my Fork](https://github.com/adrianschulz/collective.solr/pull/1/files) . 

@tisto Do you think this could be helpful for others? If so I could improve the code so I would pass the tests. Of course the default would be form another field in the control-panel (default core) and not hard-coded.

**Comment by laulaz** [comment]
See #313 👍

**Comment by laulaz** [comment]
@adrianschulz This has been merged and released in 9.0.0a6 👍
