### ISSUE TITLE
what if Solr is on another machine?

### ISSUE THREAD

**Issue by sauzher** [collective/collective.solr#28]
Indexing binary files does not work.

But I found that in collective.solr.indexer
line 121
```python
--        postdata['stream.file'] = self.getpath()
++        postdata['stream.url'] = self.context.absolute_url()
```
it works.
The server must "see" each other on the networks of course.

**Comment by tomgross** [comment]
@SauZheR You need to mount the blobstorage directory on the Solr machine via NFS or CIFS.

**Comment by loechel** [comment]
That needs to be documented. @pilz @tisto @saily #49 should include this.

**Comment by davidamoros** [comment]
@tomgross What would be the correct mounting? The path should be the same on both servers?

**Comment by sroney5250** [comment]
@davidamoros Did you ever get plone file indexing working when solr was on a different machine?  I am getting this error:
2016-05-19 14:23:29 WARNING collective.solr.indexer Error HTTP code=500, reason=Server Error @ /Plone/test

**Comment by tomgross** [comment]
@davidamoros Yes it is absolutely necessary the blob paths are **exactly the same on both machines**.

**Comment by tisto** [comment]
@tomgross maybe we should add that information to the docs...

**Comment by tomgross** [comment]
It is documented here: https://training.plone.org/5/solr-training/production-setup.html#different-host-setup

**Comment by gforcada** [comment]
Then we need to point to the training docs on our README as well
