### ISSUE TITLE
Problem with indexing empty lists / tuple (`None`) in Solr string fields

### ISSUE THREAD

**Issue by laulaz** [collective/collective.solr#366]
Empty Dexterity fields of type List / Tuple (= `None`) are indexed by `collective.solr` in the `<add>` like this :
```
<field name="my_field" update="set">None</field>
```

As it is defined in Solr schema as string fields, we end up with : 
```
<arr name="my_field">
      <str>None</str>
</arr>
```

After `catalog.searchResults`, the returned indexed value is `["None"]`.
We should have no `arr` instead.

It works correctly for List / Tuple fields (like Plone `Subjects`) only when there is a `missing_value=()` or `missing_value=[]`.

**Comment by tisto** [comment]
@reebalazs didn't we fix this problem recently?

**Comment by davisagli** [comment]
This was fixed in https://github.com/collective/collective.solr/pull/370 and released in collective.solr 9.2.1
