### ISSUE TITLE
ImportError: IIndexableObjectWrapper in Plone5

### ISSUE THREAD

**Issue by allusa** [collective/collective.solr#44]
It doesn't work on Plone5 as there is no plone.app.content.interfaces.IIndexableObjectWrapper.

**Comment by gforcada** [comment]
A grep over the source code shows that this is now on plone.indexer: https://github.com/plone/plone.indexer/blob/master/plone/indexer/interfaces.py#L7

**Comment by allusa** [comment]
Fixed in 71443fd4ebcd4556624902061299683f5485d4fa and in  791a1c8cd6e02517f02179d149438c3bf81bb7c8
