### ISSUE TITLE
Update search view to work with Plone > 4.0.

### ISSUE THREAD

**Issue by tisto** [collective/collective.solr#46]
The search view that c.solr overrides is outdated. It still uses the old "search" view instead of the newer "@@search". We should create a new view that supports facets, autocomplete and suggest.

**Comment by loechel** [comment]
@pilz and @reinhardt have build a search view for our project. If we could generalize that or write a more up to date and general search view for c.solr that we could use out of the box or with very little modification would be good. 

All of the Features: Facets, auto complete (type ahead) and suggest is needed in our project but not fully implemented now. The more open and community approach here is preferred.

**Comment by tisto** [comment]
@loechel Problem is that we would need a customization that works for both Plone 4 and 5. An option could be to remove the search view customization and provide that functionality in an add-on product.

You don't need autocomplete if your backend and your frontend is fast enough to show the results in almost real-time. If we would move to a state-of-the art js solution, autocomplete wouldn't be necessary (at least this is my experience with an Angular frontend and a Solr backend).

**Comment by tomgross** [comment]
There is a new search view for Plone 4 and 5 in c.solr 6.0
and there is an example on how to create a search view with autocomplete, suggest and facetting in the Solr training https://training.plone.org/5/solr-training/a-fancy-custom-search-page.html
