### ISSUE TITLE
Move @@solr-controlpanel to use plone.app.registry.

### ISSUE THREAD

**Issue by tisto** [collective/collective.solr#50]

**Comment by loechel** [comment]
Did I understand that right, that you like to have the storing backend moved from atrribute storrage to plone.app.registry storage?

That would be a consequent move. If you think of removing the solr control panel that is something I wouldn't like. The control panel might should move to current state of the art form lib.

**Comment by tisto** [comment]
I want to keep the solr control panel of course. This is just about storing the settings in plone.app.registry.

**Comment by tisto** [comment]
Fixed in master.
