### ISSUE TITLE
BinaryAdder write on Solr before the end (commit) of Zope's transaction

### ISSUE THREAD

**Issue by mamico** [collective/collective.solr#65]
The case is:

create a File object
do a catalog search during same Zope transaction, this will fire the emptying indexing queue by collective.indexing and a call to BinaryAdder that do a doPost (update/extract method) on Solr
abort the Zope’s transaction

Now the problem is that the file is indexed on Solr, but not exists on Zope DB.

Another case:

modify an existing File
do a search catalog (again BinaryAdder sends updated data to Solr)
abort the Zope’s transaction

In this case Solr and Zope DB will have different data for same object

**Comment by tomgross** [comment]
:sweat: Oh dear!
A solution could be to extract the binary data with the https://wiki.apache.org/solr/ExtractingRequestHandler and send it to the index like any other document.

**Comment by mamico** [comment]
Something like this I had done in https://github.com/collective/collective.solr/blob/issue-52-scorched/src/collective/solr/indexer.py#L135 

In August I will have some time to align the branch. Wonderful if you have time to take a look.

**Comment by tomgross** [comment]
A fix has been merged.
