### ISSUE TITLE
Solr 5 Support

### ISSUE THREAD

**Issue by tisto** [collective/collective.solr#66]
Create a new Plone instance, enable solr, go to reindex view.

```
2015-06-25 09:20:18 ERROR Zope.SiteErrorLog 1435216818.110.045122177306 http://localhost:8080/Plone/@@solr-maintenance/reindex
Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module collective.solr.browser.maintenance, line 119, in reindex
  Module collective.solr.manager, line 138, in getSchema
  Module collective.solr.solr, line 300, in getSchema
  Module collective.solr.solr, line 116, in __errcheck
SolrException: HTTP code=500, reason=JSP support not configured
```

**Comment by tisto** [comment]
Solr 5 branch has been created: https://github.com/collective/collective.solr/tree/solr-5

Will stop working on that for now. c.r.solrinstance multi core setup requires too many changes in c.solr right now. https://github.com/collective/collective.recipe.solrinstance/issues/44

**Comment by tisto** [comment]
"JSP support not configured" is raised because the getSchema method tries to access the solr URL without providing a core. This does not work since c.r.solrinstance (or Solr 5) forces a multi core setup.

**Comment by tomgross** [comment]
We are on Solr 6 meanwhile.

**Comment by tisto** [comment]
@tomgross with c.r.solrinstance?

**Comment by tomgross** [comment]
@tisto No. I don'^t think so but upstream.
